replicaCount: 2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

ingress:
  enabled: true
  # Replace with your staging host(s)
  hosts:
    - host: "staging.example.local"
  tls:
    - secretName: "frontend-tls"
      hosts:
        - "staging.example.local"
